[local]

; # inline host var - set directly on the host line, beats [local:vars] and [all:vars]

; localhost ansible_connection=local app_name="value_from_ini_inline_host"
localhost ansible_connection=local

; Grouped variable
; [local:vars]
; app_name="value_from_ini_groupedhosts"


; all host variable
; [all:vars]
; app_name="value_from_ini_allhosts"