- name: Setup nginx in docker
  hosts: servers
  become: true
  
  tasks:
    - name: Install docker
      apt:
        name: docker.io
        state: present
        update_cache: yes  # update pkgs ~ apt update

    # 
    - name: Pull nginx image
      command: docker pull nginx:latest
    - name: List docker images
      command: docker images
    - name: Run container
      command: docker run -d -p 80:80 nginx:latest
